#!/usr/bin/env python3
"""Build the small copies the grids actually need.

Every photograph here is about 901x1600 and every painting 1024x1536. A card
in the catalogue is 110 pixels wide on a phone, so showing it the full file
makes the browser download a quarter of a megabyte and then decode 1.4
megapixels to paint a thumbnail - times several hundred cards as you scroll.
That is what made the site crawl on a phone.

This writes a 480-pixel-tall copy of every image into images/thumbs/, keeping
the same relative path, which is what the grids, the plate strip and the
museum frames load. The full file is still what opens when you tap something.

    python3 tools/thumbs.py            # only what is missing or out of date
    python3 tools/thumbs.py --all      # rebuild everything

Needs Pillow: pip install pillow
"""
import io
import os
import sys
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "images")
OUT = os.path.join(SRC, "thumbs")
HEIGHT = 480          # tall enough for the widest frame on the site (320px)
QUALITY = 72

force = "--all" in sys.argv
made = skipped = 0
wide = []              # landscape images, recorded so the page need not measure

for dirpath, dirnames, filenames in os.walk(SRC):
    if os.path.abspath(dirpath).startswith(os.path.abspath(OUT)):
        continue
    dirnames[:] = [d for d in dirnames if d != "thumbs"]
    for name in filenames:
        if not name.lower().endswith((".jpg", ".jpeg", ".png")):
            continue
        src = os.path.join(dirpath, name)
        rel = os.path.relpath(src, SRC)
        with Image.open(src) as probe:
            if probe.width > probe.height:
                wide.append("images/" + rel.replace(os.sep, "/"))
        dst = os.path.join(OUT, os.path.splitext(rel)[0] + ".jpg")
        if not force and os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(src):
            skipped += 1
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        im = Image.open(src).convert("RGB")
        if im.height > HEIGHT:
            im = im.resize((max(1, round(im.width * HEIGHT / im.height)), HEIGHT), Image.LANCZOS)
        im.save(dst, quality=QUALITY, optimize=True, progressive=True)
        made += 1

# Which photographs are landscape is a fact about the files, so it is worked
# out here once rather than by every phone that opens the catalogue. The grid
# used to attach a load handler to all eight hundred images and toggle a class
# when each one arrived, which is a thousand style invalidations in the middle
# of a scroll.
with io.open(os.path.join(ROOT, "data", "wide.js"), "w", encoding="utf-8") as fh:
    fh.write("/* Generated by tools/thumbs.py - do not edit.\n"
             "   The landscape images: group shots and the like, which fit inside\n"
             "   their tile instead of filling it. */\n"
             "window.WIDE = [\n")
    for w in sorted(wide):
        fh.write('  "%s",\n' % w)
    fh.write("];\n")

total = sum(os.path.getsize(os.path.join(d, f))
            for d, _, fs in os.walk(OUT) for f in fs)
print(f"wide images: {len(wide)}")
print(f"thumbs: {made} written, {skipped} already current, "
      f"{total/1e6:.1f} MB in images/thumbs/")
